### ISSUE TITLE
[Bug] Generated incorrect gadgets

### ISSUE THREAD

**Issue by n132** [zolutal/kropr#1]
Hi, I found some cases that Kropr gave wrong gadgets
```c
[21:27:24] n132 :: xps  ➜  KernelExploitation/8/challenge ‹main› » cat ./dumped2 | grep ": pop rdi; ret" 
...
0xffffffff81dc55bd: pop rdi; ret;
```
```
   0xffffffff81dc55bd <__traceiter_cfg80211_rx_spurious_frame+61>    int3   
   0xffffffff81dc55be <__traceiter_cfg80211_rx_spurious_frame+62>    int3   
   0xffffffff81dc55bf <__traceiter_cfg80211_rx_spurious_frame+63>    int3   
   0xffffffff81dc55c0 <__traceiter_cfg80211_rx_spurious_frame+64>    int3   
   0xffffffff81dc55c1                                                nop    word ptr cs:[rax + rax]
   0xffffffff81dc55cc                                                nop    dword ptr [rax]
```
It could be a bug.

**Comment by zolutal** [comment]
I think this is likely due to a relocation or other self-patching the kernel does, unfortunately this is common and there isn't much that can be done about it. 

Actually now that I think of it maybe there is some way to figure out the relocation sites from some part of the kernel image? that could reduce quite a few of these false positives if it is possible...

Anyways, if you want more stable gadgets, and the kernel is compiled with thunked returns, you should prefer gadgets ending in a jump to the return thunk over other gadgets that end in a normal ret, in my experience those gadgets are more likely to be present at runtime.

**Comment by n132** [comment]
Thanks so much!

**Comment by zolutal** [comment]
Partially fixed by: https://github.com/zolutal/kropr/commit/ca286bb894d865297e1b37b5f434a386bcc0fcd3!

I think the example you provided is due to a gadget being found in a jump to the return thunk, the new default behavior is to patch all return thunks jumps to `ret; int3; int3 ; int3; int3;` to match the kernel's behavior when thunked returns are disabled at runtime, hopefully removing some false positives.

There can still be false positives from .altinstructions patches, .retpoline_sites patches, and potentially a few other sources though. I may look into handling .retpoline_sites at some point but .atinstructions is going to be a bit harder to deal with.

**Comment by n132** [comment]
Thanks for the awesome improvement!
